workflows:
  android-native-workflow:
    name: Build Android Native App
    instance_type: windows_x2
    environment:
      vars:
        ANDROID_KEYSTORE_PATH: $FCI_BUILD_DIR/android/keystore.jks
        ANDROID_KEYSTORE_PASSWORD: your_keystore_password
        ANDROID_KEY_ALIAS: your_key_alias
        ANDROID_KEY_PASSWORD: your_key_password
    scripts:
      - name: Set up Android environment
        script: |
          echo "Setting up Android environment..."
          sdkmanager --update
          sdkmanager "build-tools;33.0.0" "platforms;android-33" "platform-tools"

      - name: Install dependencies
        script: |
          ./gradlew dependencies

      - name: Build APK
        script: |
          ./gradlew assembleRelease

      - name: Build AAB
        script: |
          ./gradlew bundleRelease

    artifacts:
      - build/outputs/apk/release/*.apk
      - build/outputs/bundle/release/*.aab

    publishing:
      email:
        recipients:
          - your_email@example.com
